environment:
  BINSTAR_TOKEN:
    secure: F9q+hDZmW8jW5P+XgXS+t+hIoA2HZFK0KjG2xo77nUPBWHSZ2d/1R8MXFriQy7N6

  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

install:
  - powershell .\\.ci\\appveyor\\install.ps1

build_script:
  - powershell .\\.ci\\appveyor\\build.ps1

artifacts:
  - path: '*.tar.bz2'

on_success:
  - powershell .\\.ci\\appveyor\\deploy.ps1
