language: python

env:
  global:
    secure: eg6HZ9JP/Upcjy+8xyPECTQH2J0cvdRJOaaAtbtFfe+Lr7Bf4N4cI09byAd2k+MTWsTl8eL1Ia7Q1bYjNmE6a296qSVOrSyYurFNCWCMjuvuvtDkuyjqoB7JLXxHMOAOVw7FWtpJOO1JH7MJCUnPAFjlBPh4AVLWC1QrtDGig6XjURq0GdZLGbP0EMtLivIcvEnUm12xXRm9BKwcNmQOWxUKXpWXD7f2gCY/Xwnw8mUDrRoBJl/AM1iAiEgt1VYXs4enosa90B99P1mqhCHnpvRqhw9slXFnlBWVy0T2tKvb+4/uKHbBMrcE5cMqalq5Uvn3k9kYL7ZXuh/AFZDVG63pOHBumhRIU0EEMWsAip7Q/C8xfq+24KEKX1rMrCbftOzp0USq3CJLsk9DYvcYQ4HwMaEd+K98W1oRgMJ87Hja34TaaccxWM751J6JlrJKQXz92kPFnVSUiVuRPoqwYUV8IRioHsWxm7+p/xNV/1b3A24+JYPmi0a9Fkbvf7FKiB8Om057XCUUQH/D9rabVbBUYepCU0MCUJcnD3CzdZaJoWHry6Za2r0h+TbWiEu/G/XDlH33TlcRP918fdbzO8qCVFKwaTgstpLchrjz7zxXGhWe+Kz+Z8xx4f8OfZoIVb/LkeKc78qzRxmaaFDafQr4ewP1J5SvCWPjp/jZ5wY=

python:
  - '3.5'

install:
  - source ./.ci/travis/install.sh

script:
  - source ./.ci/travis/build.sh

after_success:
  - source ./.ci/travis/deploy.sh
