package:
  name: elemental-core
  version: "0.2.0dev0"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - elemental_core

about:
  home: https://github.com/artplusplus/elemental-core.
  summary: elemental-core contains functionality shared across Elemental CMS.
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE
